##Description - This YAML config file is used to configure input parameters
#               for the UKCloud transfer automated transfer script originally
#               developed for the StratMed PAEDs project.

#By: Sabri Jamal
#Date: 20191121
#Version: 1.0

#Sample sheet columns
sample-sheet:
  suffix: hpc.csv
  bedfile_col:  target_bed
  pool_id_col: pool_id
  sample_name_col:  samp_name
  sample_pair_name_col: gatk_grp
  sample_type:  tag

#Panels to be checked for transfer
panels:
  paediatric: PAED2

#Log file tracking record of changes
log_files:
  transfer_log:  samples_ready_to_transfer.log

#All file system objects incl files & folders
file_system_objects:
  analysis_folder_root_path: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/001.reports
  sample_sheet_path:  /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/0.samplesheets
  logfile_dest_path:  /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/UKCloud
  analysis_reports_folder: Reports
  uk_cloud_transfer_script: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/9.scripts/UKCloud-transfer-StratMedPAED/scripts/transfer_script.sh
