##Description - This YAML config file is used to configure input parameters
#               for the UKCloud transfer automated transfer script originally
#               developed for the StratMed PAEDs project.

#By: Sabri Jamal
#Date: 20191121
#Version: 1.0

#Sample sheet columns
sample-sheet:
  suffix: hpc.csv
  bedfile_col:  target_bed
  pool_id_col: pool_id
  sample_name_col:  samp_name
  sample_pair_name_col: gatk_grp
  sample_type:  tag
  wild_card_col: other
  sequencing_methodology: seq_type

#Panels to be checked for transfer
panels:
  paediatric: PAED2
  exome: IDTExome
  
#Tags
tags:
    primary: Primary
    stdout: out
    script_finish_title: Tool returned
    script_finish_tag: SUCCESS

#Log file tracking record of changes
log_files:
  transfer_log:  samples_ready_to_transfer.log

#All file system objects incl files & folders
file_system_objects:
  #analysis_folder_root_path: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/001.reports
  analysis_folder_root_path: /Users/sjamal/Documents/Work/9.Git_scripts/UKCloud-transfer-StratMedPAED/ignore/001.reports
  #scratch_analysis_folder_root_path: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/3.analysis
  scratch_analysis_folder_root_path: /Users/sjamal/Documents/Work/9.Git_scripts/UKCloud-transfer-StratMedPAED/ignore/3.analysis
  #sample_sheet_path:  /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/0.samplesheets
  #sample_sheet_path:  /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/0.samplesheets/Test_SS_UKCloud 
  sample_sheet_path: /Users/sjamal/Documents/Work/9.Git_scripts/UKCloud-transfer-StratMedPAED/ignore/0.samplesheets/test_area
  #logfile_dest_path:  /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/UKCloud
  logfile_dest_path: /Users/sjamal/Documents/Work/9.Git_scripts/UKCloud-transfer-StratMedPAED/ignore/UKCloud
  analysis_reports_folder: Reports
  uk_cloud_transfer_script: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/9.scripts/UKCloud-transfer-StratMedPAED/scripts/transfer_script.sh
  #fastq_analysis_folder_root_path: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/003.Fastqs
  fastq_analysis_folder_root_path: /Users/sjamal/Documents/Work/9.Git_scripts/UKCloud-transfer-StratMedPAED/ignore/003.Fastqs
  fastq_ready_file: fastq.ready
  uk_cloud_transfer_fastq_script: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/9.scripts/UKCloud-transfer-StratMedPAED/scripts/transfer_fastq_script.sh
  scripts_direc: scripts
  script_variant_call: snv
  uk_cloud_transfer_tonly_not_checked_script: /scratch/DMP/DUDMP/TRANSGEN/transgen-mdx/ngs/9.scripts/UKCloud-transfer-StratMedPAED/scripts/transfer_tonly_not_checked_script.sh
